//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault
    {
        public System.Guid Referencenumber { get; set; }
        public string Logger { get; set; }
        public System.DateTime Time { get; set; }
        public string TypeofFault { get; set; }
        public string FaultDescription { get; set; }
    }
}
